### ISSUE TITLE
Upload example in README

### ISSUE THREAD

**Issue by ccpowers** [foxglove/py-data-platform#2]
Can you add an example of using the client to upload a bag to the data platform in the README? I'd like to try it out but want to make sure i'm using the client correctly.

**Comment by foxymiles** [comment]
@ccpowers I've added an `examples` directory and added an upload example. Does that help?

**Comment by foxymiles** [comment]
@ccpowers Sure I'll add an example of bag files too.

**Comment by foxymiles** [comment]
@ccpowers I've added an example of a .bag file upload to the upload example. The code is almost the same since data platform will automatically detect the file type and process it accordingly whether it's mcap or a ros1 bag.

**Comment by ccpowers** [comment]
@foxymiles thank you!
