### ISSUE TITLE
Add "delete device" to client

### ISSUE THREAD

**Issue by esthersweon** [foxglove/py-data-platform#20]

**Comment by foxymiles** [comment]
@esthersweon @bryfox It looks like the API doesn't support this yet?

**Comment by bryfox** [comment]
Correct, there's no such endpoint. I'll see what's involved here — Console would likely need to coordinate with Data Platform.

**Comment by bryfox** [comment]
Depends on https://github.com/foxglove/console/issues/679

**Comment by bryfox** [comment]
This is available in the API as of https://github.com/foxglove/console/pull/788
