### ISSUE TITLE
Add "delete import" to client

### ISSUE THREAD

**Issue by esthersweon** [foxglove/py-data-platform#21]

**Comment by foxymiles** [comment]
@esthersweon I don't think the API currently supports this. Can you confirm @bryfox?

**Comment by bryfox** [comment]
Not yet supported for API keys, but I can add that pretty quickly. Note that today, we only have soft deletion implemented;  I don't think that would matter for casual use, but it might be worth calling out.

**Comment by foxymiles** [comment]
@bryfox I agree it makes sense to wait instead of publishing then changing the API.

**Comment by bryfox** [comment]
Looks like this was added in v0.1.0, and is documented: https://foxglove.dev/docs/data-platform/api/data#delete-import
