### ISSUE TITLE
Pip install doens't grab typing-extensions dependency

### ISSUE THREAD

**Issue by AndrewNolte** [foxglove/py-data-platform#28]
**Description**
Although I see it in some of the pypi files, [typing extensions](https://pypi.org/project/typing-extensions/) doesn't seem to be getting downloaded when pip installing foxglove-data-platform

- Version: 0.1.0
- Platform: Ubuntu 20.04, Mac

**Steps To Reproduce**
Make sure that typing-extensions isn't already installed (pip list, pip uninstall)
Run `pip install foxglove-data-platform`
Verify with `pip list` that typing-extensions isn't installed

**Expected Behavior**
It's installed

**Actual Behavior**
It's not

**Ideas for solutions**

* Upgrade to python 3.8, where Protocol is in the typing package
* Debug issue with pip not installing the dependency
* have a try/except statement that tries to import it from `typing` first, then tries `typing-extensions` if that fails

**Comment by AndrewNolte** [comment]
Actually in client.py pretty sure this line implies that it needs >=3.8, as I don't think there's a protocol class in 3.7
`from typing import IO, Any, Dict, List, Optional, Protocol, Union, cast`

**Comment by foxymiles** [comment]
@AndrewNolte Are you possibly looking at an old version of the library? These are the current client.py imports:

https://github.com/foxglove/py-data-platform/blob/c44b72c121ce043e58cb174aaf43a012a71283a6/foxglove_data_platform/client.py#L1-L10
