### ISSUE TITLE
`topics` arg for downloading data should be optional, like REST API endpoint

### ISSUE THREAD

**Issue by esthersweon** [foxglove/py-data-platform#33]
**Description**
- `topics` arg for downloading data should be optional (to correspond with REST API)
Code in question: https://github.com/foxglove/py-data-platform/blob/main/foxglove_data_platform/client.py#L284

**Comment by bryfox** [comment]
The arg has a default assignment and the docstring looks OK. Is this not working as expected? Or is this related to possible upcoming changes mentioned here https://foxgloveden.slack.com/archives/C02EEA68XJT/p1648252210765229?thread_ts=1648248229.319079&cid=C02EEA68XJT?

**Comment by foxymiles** [comment]
https://github.com/foxglove/py-data-platform/blob/efe360c2d31726bb50ad5ebe276e8d08f44dad2e/foxglove_data_platform/client.py#L283-L285

This argument is optional now. Omitting it will give you all topics.
