### ISSUE TITLE
`get_topics` call should have an optional `includeSchemas` arg, to correspond with REST API call

### ISSUE THREAD

**Issue by esthersweon** [foxglove/py-data-platform#34]
**Description**
- `get_topics` call should have an optional `includeSchemas` arg, to correspond with REST API call

Code in question: https://github.com/foxglove/py-data-platform/blob/main/foxglove_data_platform/client.py#L450

**Comment by foxymiles** [comment]
I left this out since it can potentially be a fair bit of data and not that useful for typical users of this library that might accidentally turn this on. Maybe I'm guessing wrong?

**Comment by defunctzombie** [comment]
Fixed in https://github.com/foxglove/py-data-platform/pull/72
