### ISSUE TITLE
Support get_messages() for ROS 2 data

### ISSUE THREAD

**Issue by amacneil** [foxglove/py-data-platform#53]
Several customers have asked for the ability to iterate ROS 2 data directly using the `get_messages()` API.

Currently, `get_messages()` is only supported for ROS 1 data. For ROS 2, the only workaround is to download the raw mcap data using `download_data()`, then parse it using `mcap` and `rclpy`, which is pretty cumbersome. This would be slightly nicer if we at least had a way to iterate raw message data for unsupported serialization formats.

**Comment by MathiasThor** [comment]
We are also facing this issue - would indeed be nice with support for ROS2.

**Comment by amacneil** [comment]
Now that https://github.com/foxglove/mcap/pull/641 is merged, this should be a simple lift. @defunctzombie @bryfox can someone from data paltform take a look?

cc @jhurliman

**Comment by defunctzombie** [comment]
@amacneil I suggest we put this into the mcap developer experience epic. @james-rms sending your way for scoping and assignment.

**Comment by james-rms** [comment]
Implemented as of `foxglove-data-platform` version 0.2.0.
